-- ==========================================
-- GEOSURVEY PRO DATABASE SCHEMA FOR SUPABASE
-- ==========================================

-- Enable PostGIS extension if needed for spatial coordinates (optional, we use text coordinates to match the original app, but this enables future spatial queries)
CREATE EXTENSION IF NOT EXISTS postgis;

-- 1. PROFILES TABLE (linked to Supabase Auth users)
CREATE TABLE public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    username VARCHAR(255) UNIQUE NOT NULL,
    fullname VARCHAR(255) NOT NULL,
    role VARCHAR(50) DEFAULT 'User' CHECK (role IN ('Admin', 'User')),
    permitted_menus TEXT[] DEFAULT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Enable Row Level Security (RLS) on profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Create policies for profiles
CREATE POLICY "Public profiles are viewable by authenticated users" 
    ON public.profiles FOR SELECT TO authenticated USING (true);

CREATE POLICY "Users can update their own profile" 
    ON public.profiles FOR UPDATE TO authenticated USING (auth.uid() = id);

CREATE POLICY "Admins can do everything on profiles" 
    ON public.profiles FOR ALL TO authenticated USING (
        (auth.jwt() -> 'user_metadata' ->> 'role') = 'Admin'
    );

-- 2. LAND SURVEYS TABLE (Diiwaangelinta Sahanka)
CREATE TABLE public.surveys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    serial_no INT NOT NULL UNIQUE, -- Somali: S/N
    owner_name VARCHAR(255) NOT NULL, -- Somali: Magaca Milkiilaha
    neighborhood VARCHAR(100) NOT NULL, -- Somali: Xaafadda
    branch VARCHAR(100) NOT NULL, -- Somali: Laanta
    vicinity VARCHAR(255), -- Somali: Nawaaxiga
    land_type VARCHAR(100) NOT NULL, -- Somali: Nooca Dhulka (Dhul Banaan / Dhul dhisan)
    built_details VARCHAR(255), -- Somali: Waxa ku dhisan
    -- Boundaries (Cabirka & Deriska)
    boundary_w_val VARCHAR(100),
    boundary_w_neighbor VARCHAR(255),
    boundary_b_val VARCHAR(100),
    boundary_b_neighbor VARCHAR(255),
    boundary_k_val VARCHAR(100),
    boundary_k_neighbor VARCHAR(255),
    boundary_g_val VARCHAR(100),
    boundary_g_neighbor VARCHAR(255),
    -- Geo Details
    gps_location VARCHAR(100), -- Coords e.g. "3.1192, 43.6498"
    polygon_boundary TEXT, -- Coords path separated by semi-colon
    sketch_area VARCHAR(100),
    sketch_dimensions TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_by UUID REFERENCES auth.users(id)
);

ALTER TABLE public.surveys ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can view surveys" 
    ON public.surveys FOR SELECT TO authenticated USING (true);

CREATE POLICY "Authenticated users can insert surveys" 
    ON public.surveys FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Authenticated users can update surveys" 
    ON public.surveys FOR UPDATE TO authenticated USING (true);

CREATE POLICY "Admins can delete surveys" 
    ON public.surveys FOR DELETE TO authenticated USING (
        (auth.jwt() -> 'user_metadata' ->> 'role') = 'Admin'
    );

-- 3. REFERENCES TABLE (Dukumiintiyada Tixraaca)
CREATE TABLE public.references (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ref_number VARCHAR(100) NOT NULL UNIQUE, -- Somali: Sumad
    survey_id BIGINT REFERENCES public.surveys(id) ON DELETE SET NULL, -- Connected Survey
    subject VARCHAR(255) NOT NULL, -- Somali: Ujeedo
    details TEXT, -- Somali: Faahfaahin
    status VARCHAR(50) DEFAULT 'In Progress' CHECK (status IN ('In Progress', 'Completed', 'Picked Up')),
    issue_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_by UUID REFERENCES auth.users(id)
);

ALTER TABLE public.references ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can view references" 
    ON public.references FOR SELECT TO authenticated USING (true);

CREATE POLICY "Authenticated users can insert references" 
    ON public.references FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Authenticated users can update references" 
    ON public.references FOR UPDATE TO authenticated USING (true);

-- 4. RECEIPTS TABLE (Dakhliga - Client Payments)
CREATE TABLE public.receipts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_no VARCHAR(100) NOT NULL UNIQUE,
    reference_id BIGINT REFERENCES public.references(id) ON DELETE CASCADE,
    details TEXT,
    amount NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
    status VARCHAR(50) DEFAULT 'Paid' CHECK (status IN ('Paid', 'Credit')),
    payment_mode VARCHAR(100) DEFAULT 'Cash' CHECK (payment_mode IN ('EVC Plus', 'eDahab', 'Jeeb', 'Cash')),
    payment_date DATE DEFAULT CURRENT_DATE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_by UUID REFERENCES auth.users(id)
);

ALTER TABLE public.receipts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can view receipts" 
    ON public.receipts FOR SELECT TO authenticated USING (true);

CREATE POLICY "Authenticated users can insert receipts" 
    ON public.receipts FOR INSERT TO authenticated WITH CHECK (true);

-- 5. EXPENSES TABLE (Kharashka - Office Expenses)
CREATE TABLE public.expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description TEXT NOT NULL,
    qty INT NOT NULL DEFAULT 1,
    amount NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
    total NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
    expense_date DATE DEFAULT CURRENT_DATE,
    created_by VARCHAR(255), -- Storing creator's name or UUID
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE public.expenses ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can view expenses" 
    ON public.expenses FOR SELECT TO authenticated USING (true);

CREATE POLICY "Authenticated users can insert expenses" 
    ON public.expenses FOR INSERT TO authenticated WITH CHECK (true);

-- 6. LAND TRANSFERS TABLE (Wareejinta Dhulka)
CREATE TABLE public.transfers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    serial_no INT NOT NULL,
    seller_name VARCHAR(255) NOT NULL, -- Somali: Iibiyaha
    seller_tel VARCHAR(50) NOT NULL, -- Somali: Tel Iibiyaha
    buyer_name VARCHAR(255) NOT NULL, -- Somali: Iibsadaha
    buyer_tel VARCHAR(50) NOT NULL, -- Somali: Tel Iibsadaha
    survey_id BIGINT REFERENCES public.surveys(id) ON DELETE SET NULL, -- Connected Survey
    price NUMERIC(12, 2) NOT NULL DEFAULT 0.00, -- Somali: Lacagta
    transfer_date DATE DEFAULT CURRENT_DATE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_by UUID REFERENCES auth.users(id)
);

ALTER TABLE public.transfers ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can view transfers" 
    ON public.transfers FOR SELECT TO authenticated USING (true);

CREATE POLICY "Authenticated users can insert transfers" 
    ON public.transfers FOR INSERT TO authenticated WITH CHECK (true);


-- 7. TRIGGERS FOR PROFILE CREATION ON USER SIGNUP (Automated helper)
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.profiles (id, username, fullname, role)
    VALUES (
        new.id,
        COALESCE(new.raw_user_meta_data->>'username', split_part(new.email, '@', 1)),
        COALESCE(new.raw_user_meta_data->>'fullname', split_part(new.email, '@', 1)),
        COALESCE(new.raw_user_meta_data->>'role', 'User')
    );
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
