-- Document Archive: lets staff upload a scanned PDF of a reference's original paper
-- document, stored in a dedicated Google Drive account (separate from the read-only
-- search-index Drive connections, which live in their own Supabase project). Scanning a
-- reference's QR code (the existing public verify page) can then download this PDF.

ALTER TABLE public.references
  ADD COLUMN IF NOT EXISTS archive_drive_file_id TEXT,
  ADD COLUMN IF NOT EXISTS archive_file_name TEXT,
  ADD COLUMN IF NOT EXISTS archive_uploaded_at TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS archive_uploaded_by UUID REFERENCES auth.users(id);

-- Single-row table holding the archive Drive account's service-account credentials and
-- destination folder. Same access pattern as drive_connections: server-only via
-- SUPABASE_SERVICE_ROLE_KEY, RLS enabled with no policies granted to anon/authenticated.
CREATE TABLE IF NOT EXISTS public.archive_drive_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_email VARCHAR(255) NOT NULL,
    private_key TEXT NOT NULL,
    root_folder_id VARCHAR(120) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE public.archive_drive_settings ENABLE ROW LEVEL SECURITY;
