-- Per-user record notifications. A notification row is created only for staff who can
-- open the corresponding menu, so RLS and menu permissions agree by construction.
CREATE TABLE IF NOT EXISTS public.app_notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipient_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  menu_path TEXT NOT NULL,
  entity_type TEXT NOT NULL,
  entity_id BIGINT NOT NULL,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  href TEXT NOT NULL,
  read_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (recipient_id, entity_type, entity_id)
);

CREATE INDEX IF NOT EXISTS app_notifications_recipient_idx
  ON public.app_notifications(recipient_id, created_at DESC);

ALTER TABLE public.app_notifications ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can read their own notifications" ON public.app_notifications;
DROP POLICY IF EXISTS "Users can update their own notifications" ON public.app_notifications;
CREATE POLICY "Users can read their own notifications" ON public.app_notifications
  FOR SELECT TO authenticated USING (recipient_id = auth.uid());
CREATE POLICY "Users can update their own notifications" ON public.app_notifications
  FOR UPDATE TO authenticated USING (recipient_id = auth.uid())
  WITH CHECK (recipient_id = auth.uid());

CREATE OR REPLACE FUNCTION public.enqueue_menu_notification(
  target_menu TEXT,
  target_entity_type TEXT,
  target_entity_id BIGINT,
  notification_title TEXT,
  notification_body TEXT,
  target_href TEXT
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.app_notifications(
    recipient_id, menu_path, entity_type, entity_id, title, body, href
  )
  SELECT
    profile.id,
    target_menu,
    target_entity_type,
    target_entity_id,
    notification_title,
    notification_body,
    target_href
  FROM public.profiles AS profile
  WHERE profile.role IN ('Admin', 'SuperAdmin')
     OR target_menu = ANY(COALESCE(profile.permitted_menus, ARRAY[]::TEXT[]))
  ON CONFLICT (recipient_id, entity_type, entity_id) DO NOTHING;

END;
$$;

CREATE OR REPLACE FUNCTION public.notify_new_survey_record()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  PERFORM public.enqueue_menu_notification(
    '/records', 'survey', NEW.id,
    'Survey cusub ayaa la diiwaangeliyey',
    'Survey ' || COALESCE(NEW.survey_no, NEW.serial_no::TEXT) || ' - ' || NEW.owner_name,
    '/records'
  );
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.notify_new_reference_record()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  PERFORM public.enqueue_menu_notification(
    '/references', 'reference', NEW.id,
    'Reference cusub ayaa la sameeyey',
    COALESCE(NEW.ref_number, 'Reference') || ' - ' || COALESCE(NEW.subject, ''),
    '/references'
  );
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.notify_new_transfer_record()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  PERFORM public.enqueue_menu_notification(
    '/transfers', 'transfer', NEW.id,
    'Wareejin dhul oo cusub ayaa la diiwaangeliyey',
    COALESCE(NEW.seller_name, '') || ' -> ' || COALESCE(NEW.buyer_name, ''),
    '/transfers'
  );
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.notify_new_receipt_record()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  PERFORM public.enqueue_menu_notification(
    '/financials', 'receipt', NEW.id,
    'Receipt cusub ayaa la diiwaangeliyey',
    COALESCE(NEW.receipt_no, 'Receipt') || ' - $' || COALESCE(NEW.amount, 0)::TEXT,
    '/financials'
  );
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.notify_new_expense_record()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  PERFORM public.enqueue_menu_notification(
    '/financials', 'expense', NEW.id,
    'Kharash cusub ayaa la diiwaangeliyey',
    COALESCE(NEW.description, 'Expense') || ' - $' || COALESCE(NEW.total, 0)::TEXT,
    '/financials'
  );

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS surveys_create_notifications ON public.surveys;
CREATE TRIGGER surveys_create_notifications
  AFTER INSERT ON public.surveys
  FOR EACH ROW EXECUTE FUNCTION public.notify_new_survey_record();

DROP TRIGGER IF EXISTS references_create_notifications ON public.references;
CREATE TRIGGER references_create_notifications
  AFTER INSERT ON public.references
  FOR EACH ROW EXECUTE FUNCTION public.notify_new_reference_record();

DROP TRIGGER IF EXISTS transfers_create_notifications ON public.transfers;
CREATE TRIGGER transfers_create_notifications
  AFTER INSERT ON public.transfers
  FOR EACH ROW EXECUTE FUNCTION public.notify_new_transfer_record();

DROP TRIGGER IF EXISTS receipts_create_notifications ON public.receipts;
CREATE TRIGGER receipts_create_notifications
  AFTER INSERT ON public.receipts
  FOR EACH ROW EXECUTE FUNCTION public.notify_new_receipt_record();

DROP TRIGGER IF EXISTS expenses_create_notifications ON public.expenses;
CREATE TRIGGER expenses_create_notifications
  AFTER INSERT ON public.expenses
  FOR EACH ROW EXECUTE FUNCTION public.notify_new_expense_record();

REVOKE ALL ON FUNCTION public.enqueue_menu_notification(TEXT, TEXT, BIGINT, TEXT, TEXT, TEXT) FROM PUBLIC, authenticated;
REVOKE ALL ON FUNCTION public.notify_new_survey_record() FROM PUBLIC, authenticated;
REVOKE ALL ON FUNCTION public.notify_new_reference_record() FROM PUBLIC, authenticated;
REVOKE ALL ON FUNCTION public.notify_new_transfer_record() FROM PUBLIC, authenticated;
REVOKE ALL ON FUNCTION public.notify_new_receipt_record() FROM PUBLIC, authenticated;
REVOKE ALL ON FUNCTION public.notify_new_expense_record() FROM PUBLIC, authenticated;

-- Supabase Realtime delivers each recipient's new row immediately. Ignore the duplicate
-- object error when the table was already added to the publication manually.
DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE public.app_notifications;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

GRANT SELECT, UPDATE ON public.app_notifications TO authenticated;
