-- Named Google Drive connections: lets the notary office register several separate
-- Google service-account credentials (e.g. one per branch/office), each pointing at its
-- own shared folder, and pick between them when browsing/searching Drive.
--
-- This table holds a private key per row, so it is never queried directly by the browser
-- client (anon/authenticated Supabase keys). All access goes through server-side API
-- routes using SUPABASE_SERVICE_ROLE_KEY, which bypasses RLS — so RLS is enabled here
-- with no policies granted to anon/authenticated, denying all direct client access.

CREATE TABLE public.drive_connections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    client_email VARCHAR(255) NOT NULL,
    private_key TEXT NOT NULL,
    root_folder_id VARCHAR(120) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE public.drive_connections ENABLE ROW LEVEL SECURITY;
