-- Native push tokens belong to exactly one signed-in profile. Registration is exposed
-- through a SECURITY DEFINER RPC so the same physical device can safely change users.
CREATE TABLE IF NOT EXISTS public.push_device_tokens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipient_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  token TEXT NOT NULL UNIQUE,
  platform TEXT NOT NULL CHECK (platform IN ('android', 'ios')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS push_device_tokens_recipient_idx
  ON public.push_device_tokens(recipient_id);

ALTER TABLE public.push_device_tokens ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can read their own push tokens" ON public.push_device_tokens;
DROP POLICY IF EXISTS "Users can delete their own push tokens" ON public.push_device_tokens;
CREATE POLICY "Users can read their own push tokens" ON public.push_device_tokens
  FOR SELECT TO authenticated USING (recipient_id = auth.uid());
CREATE POLICY "Users can delete their own push tokens" ON public.push_device_tokens
  FOR DELETE TO authenticated USING (recipient_id = auth.uid());

CREATE OR REPLACE FUNCTION public.register_push_device_token(
  target_token TEXT,
  target_platform TEXT
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  viewer_id UUID := auth.uid();
BEGIN
  IF viewer_id IS NULL THEN
    RAISE EXCEPTION 'Authentication required';
  END IF;
  IF NULLIF(TRIM(target_token), '') IS NULL THEN
    RAISE EXCEPTION 'Push token is required';
  END IF;
  IF target_platform NOT IN ('android', 'ios') THEN
    RAISE EXCEPTION 'Unsupported push platform';
  END IF;

  INSERT INTO public.push_device_tokens(recipient_id, token, platform)
  VALUES (viewer_id, TRIM(target_token), target_platform)
  ON CONFLICT (token) DO UPDATE SET
    recipient_id = EXCLUDED.recipient_id,
    platform = EXCLUDED.platform,
    updated_at = CURRENT_TIMESTAMP;
END;
$$;

REVOKE ALL ON FUNCTION public.register_push_device_token(TEXT, TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.register_push_device_token(TEXT, TEXT) TO authenticated;
GRANT SELECT, DELETE ON public.push_device_tokens TO authenticated;
