-- Local search index for Google Drive documents. Macmiisha (customer) search used to
-- download and parse every candidate document live from Drive on each query, which is
-- bandwidth-bound and could take 10-15+ seconds. This table caches each document's
-- extracted plain text so searches run against Postgres instead of Drive at query time.
-- A background sync job (triggered manually from Settings) keeps it up to date.
--
-- Same access pattern as drive_connections: server-only, via SUPABASE_SERVICE_ROLE_KEY.
-- RLS is enabled with no policies granted to anon/authenticated, denying all direct
-- client access.

CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE public.drive_document_index (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    connection_id BIGINT NOT NULL REFERENCES public.drive_connections(id) ON DELETE CASCADE,
    file_id VARCHAR(120) NOT NULL,
    file_name TEXT NOT NULL,
    web_view_link TEXT,
    modified_time TIMESTAMP WITH TIME ZONE,
    extracted_text TEXT NOT NULL,
    indexed_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (connection_id, file_id)
);

CREATE INDEX drive_document_index_text_trgm ON public.drive_document_index USING gin (extracted_text gin_trgm_ops);
CREATE INDEX drive_document_index_connection_idx ON public.drive_document_index (connection_id);

ALTER TABLE public.drive_document_index ENABLE ROW LEVEL SECURITY;
