-- GeoSurvey Pro: survey governance, audit, documents, permissions and PostGIS validation
CREATE EXTENSION IF NOT EXISTS postgis;

ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS permitted_actions TEXT[] DEFAULT ARRAY[
    'survey.create', 'survey.edit', 'survey.submit',
    'reference.manage', 'transfer.create', 'finance.manage', 'report.view'
  ]::TEXT[];

UPDATE public.profiles
SET permitted_actions = array_append(COALESCE(permitted_actions, ARRAY[]::TEXT[]), 'report.view')
WHERE role <> 'Admin' AND NOT ('report.view' = ANY(COALESCE(permitted_actions, ARRAY[]::TEXT[])));

UPDATE public.profiles
SET permitted_menus = array_append(COALESCE(permitted_menus, ARRAY[]::TEXT[]), '/reports')
WHERE role <> 'Admin' AND NOT ('/reports' = ANY(COALESCE(permitted_menus, ARRAY[]::TEXT[])));

ALTER TABLE public.surveys
  ADD COLUMN IF NOT EXISTS status VARCHAR(30) NOT NULL DEFAULT 'Draft',
  ADD COLUMN IF NOT EXISTS version INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS updated_by UUID REFERENCES auth.users(id),
  ADD COLUMN IF NOT EXISTS approved_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS approved_by UUID REFERENCES auth.users(id),
  ADD COLUMN IF NOT EXISTS rejection_reason TEXT,
  ADD COLUMN IF NOT EXISTS geom geometry(Polygon, 4326);

CREATE SEQUENCE IF NOT EXISTS public.survey_serial_no_seq;
SELECT setval(
  'public.survey_serial_no_seq',
  GREATEST(COALESCE((SELECT MAX(serial_no) FROM public.surveys), 1), 1),
  EXISTS (SELECT 1 FROM public.surveys)
);
ALTER SEQUENCE public.survey_serial_no_seq OWNED BY public.surveys.serial_no;
ALTER TABLE public.surveys ALTER COLUMN serial_no SET DEFAULT nextval('public.survey_serial_no_seq');

DO $$ BEGIN
  ALTER TABLE public.surveys ADD CONSTRAINT surveys_status_check
    CHECK (status IN ('Draft', 'Pending Review', 'Approved', 'Rejected', 'Archived'));
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS public.survey_revisions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  survey_id BIGINT NOT NULL REFERENCES public.surveys(id) ON DELETE CASCADE,
  version INTEGER NOT NULL,
  action VARCHAR(40) NOT NULL,
  notes TEXT,
  survey_snapshot JSONB NOT NULL,
  changed_fields JSONB DEFAULT '{}'::JSONB,
  changed_by UUID REFERENCES auth.users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS survey_revisions_survey_idx
  ON public.survey_revisions(survey_id, version DESC);

CREATE TABLE IF NOT EXISTS public.survey_documents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  survey_id BIGINT NOT NULL REFERENCES public.surveys(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  category VARCHAR(60) NOT NULL DEFAULT 'Other',
  storage_path TEXT NOT NULL UNIQUE,
  mime_type VARCHAR(150),
  size_bytes BIGINT NOT NULL DEFAULT 0,
  uploaded_by UUID REFERENCES auth.users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS survey_documents_survey_idx
  ON public.survey_documents(survey_id, created_at DESC);

CREATE OR REPLACE FUNCTION public.is_admin(check_uid UUID DEFAULT auth.uid())
RETURNS BOOLEAN LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = check_uid AND role = 'Admin'
  );
$$;

CREATE OR REPLACE FUNCTION public.has_action(action_name TEXT, check_uid UUID DEFAULT auth.uid())
RETURNS BOOLEAN LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT public.is_admin(check_uid) OR EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = check_uid AND action_name = ANY(COALESCE(permitted_actions, ARRAY[]::TEXT[]))
  );
$$;

CREATE OR REPLACE FUNCTION public.polygon_text_to_geometry(poly_text TEXT)
RETURNS geometry LANGUAGE plpgsql IMMUTABLE AS $$
DECLARE
  ring geometry;
BEGIN
  IF poly_text IS NULL OR btrim(poly_text) = '' THEN RETURN NULL; END IF;
  IF EXISTS (
    SELECT 1
    FROM unnest(string_to_array(poly_text, ';')) AS p(raw_point)
    WHERE btrim(raw_point) = ''
      OR split_part(raw_point, ',', 1)::DOUBLE PRECISION NOT BETWEEN -90 AND 90
      OR split_part(raw_point, ',', 2)::DOUBLE PRECISION NOT BETWEEN -180 AND 180
  ) THEN RETURN NULL; END IF;
  SELECT ST_MakeLine(ARRAY_AGG(ST_SetSRID(ST_MakePoint(
    split_part(point_text, ',', 2)::DOUBLE PRECISION,
    split_part(point_text, ',', 1)::DOUBLE PRECISION
  ), 4326) ORDER BY ordinal))
  INTO ring
  FROM unnest(string_to_array(poly_text, ';')) WITH ORDINALITY AS p(raw_point, ordinal)
  CROSS JOIN LATERAL (SELECT btrim(raw_point) AS point_text) clean;

  IF ST_NPoints(ring) < 3 THEN RETURN NULL; END IF;
  IF NOT ST_Equals(ST_StartPoint(ring), ST_EndPoint(ring)) THEN
    ring := ST_AddPoint(ring, ST_StartPoint(ring));
  END IF;
  IF NOT ST_IsValid(ST_MakePolygon(ring)) THEN RETURN NULL; END IF;
  RETURN ST_MakePolygon(ring);
EXCEPTION WHEN OTHERS THEN
  RETURN NULL;
END;
$$;

CREATE OR REPLACE FUNCTION public.sync_survey_geometry()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.geom := public.polygon_text_to_geometry(NEW.polygon_boundary);
  NEW.updated_at := CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS surveys_sync_geometry ON public.surveys;
CREATE TRIGGER surveys_sync_geometry
  BEFORE INSERT OR UPDATE OF polygon_boundary ON public.surveys
  FOR EACH ROW EXECUTE FUNCTION public.sync_survey_geometry();

UPDATE public.surveys
SET geom = public.polygon_text_to_geometry(polygon_boundary)
WHERE polygon_boundary IS NOT NULL AND geom IS NULL;

CREATE INDEX IF NOT EXISTS surveys_geom_gix ON public.surveys USING GIST (geom);

CREATE OR REPLACE FUNCTION public.check_survey_overlap(poly_text TEXT, exclude_survey_id BIGINT DEFAULT NULL)
RETURNS TABLE(id BIGINT, serial_no INTEGER, owner_name VARCHAR, overlap_area_m2 DOUBLE PRECISION)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  WITH candidate AS (SELECT public.polygon_text_to_geometry(poly_text) AS geom)
  SELECT s.id, s.serial_no, s.owner_name,
    ST_Area(ST_Intersection(s.geom, c.geom)::geography) AS overlap_area_m2
  FROM public.surveys s CROSS JOIN candidate c
  WHERE c.geom IS NOT NULL
    AND s.geom IS NOT NULL
    AND (exclude_survey_id IS NULL OR s.id <> exclude_survey_id)
    AND s.status <> 'Archived'
    AND ST_Intersects(s.geom, c.geom)
    AND ST_Area(ST_Intersection(s.geom, c.geom)::geography) > 0.05
  ORDER BY overlap_area_m2 DESC;
$$;

CREATE OR REPLACE FUNCTION public.is_survey_polygon_valid(poly_text TEXT)
RETURNS BOOLEAN LANGUAGE sql IMMUTABLE AS $$
  SELECT public.polygon_text_to_geometry(poly_text) IS NOT NULL;
$$;

CREATE OR REPLACE FUNCTION public.audit_survey_change()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  actor UUID := COALESCE(NEW.updated_by, auth.uid());
BEGIN
  IF TG_OP = 'INSERT' THEN
    INSERT INTO public.survey_revisions(survey_id, version, action, notes, survey_snapshot, changed_by)
    VALUES (NEW.id, NEW.version, 'Created', 'Survey created', to_jsonb(NEW) - 'geom', COALESCE(NEW.created_by, actor));
    RETURN NEW;
  END IF;

  IF to_jsonb(OLD) IS DISTINCT FROM to_jsonb(NEW) THEN
    INSERT INTO public.survey_revisions(survey_id, version, action, notes, survey_snapshot, changed_fields, changed_by)
    VALUES (
      OLD.id, OLD.version, CASE WHEN OLD.status IS DISTINCT FROM NEW.status THEN 'Status Changed' ELSE 'Updated' END,
      CASE WHEN OLD.status IS DISTINCT FROM NEW.status THEN OLD.status || ' -> ' || NEW.status ELSE 'Survey details updated' END,
      to_jsonb(OLD) - 'geom',
      jsonb_build_object('before', to_jsonb(OLD) - 'geom', 'after', to_jsonb(NEW) - 'geom'),
      actor
    );
  END IF;
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.bump_survey_version()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.version := OLD.version + 1;
  NEW.updated_at := CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS surveys_bump_version ON public.surveys;
CREATE TRIGGER surveys_bump_version
  BEFORE UPDATE ON public.surveys
  FOR EACH ROW EXECUTE FUNCTION public.bump_survey_version();

DROP TRIGGER IF EXISTS surveys_audit_change ON public.surveys;
CREATE TRIGGER surveys_audit_change
  AFTER INSERT OR UPDATE ON public.surveys
  FOR EACH ROW EXECUTE FUNCTION public.audit_survey_change();

ALTER TABLE public.survey_revisions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.survey_documents ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated users can insert surveys" ON public.surveys;
DROP POLICY IF EXISTS "Authenticated users can update surveys" ON public.surveys;
DROP POLICY IF EXISTS "Admins can delete surveys" ON public.surveys;

CREATE POLICY "Authorized users can insert surveys" ON public.surveys
  FOR INSERT TO authenticated WITH CHECK (public.has_action('survey.create'));
CREATE POLICY "Authorized users can edit surveys" ON public.surveys
  FOR UPDATE TO authenticated USING (public.has_action('survey.edit')) WITH CHECK (public.has_action('survey.edit'));
CREATE POLICY "Admins can delete surveys" ON public.surveys
  FOR DELETE TO authenticated USING (public.is_admin());

-- All survey mutations go through the authenticated server API. This prevents
-- callers from bypassing workflow transitions by talking to PostgREST directly.
REVOKE INSERT, UPDATE, DELETE ON public.surveys FROM authenticated;

-- The original self-update profile policy otherwise allows a user to grant
-- themselves actions or an Admin role. Profile writes are server-admin only.
REVOKE UPDATE ON public.profiles FROM authenticated;

CREATE POLICY "Authenticated users can view survey revisions" ON public.survey_revisions
  FOR SELECT TO authenticated USING (true);
CREATE POLICY "Authenticated users can view survey documents" ON public.survey_documents
  FOR SELECT TO authenticated USING (true);
CREATE POLICY "Authorized users can add survey documents" ON public.survey_documents
  FOR INSERT TO authenticated WITH CHECK (public.has_action('survey.edit'));
CREATE POLICY "Authorized users can remove survey documents" ON public.survey_documents
  FOR DELETE TO authenticated USING (public.has_action('survey.edit'));

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES ('survey-documents', 'survey-documents', false, 10485760,
  ARRAY['application/pdf','image/jpeg','image/png','image/webp'])
ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS "Authenticated users can read survey files" ON storage.objects;
DROP POLICY IF EXISTS "Authorized users can upload survey files" ON storage.objects;
DROP POLICY IF EXISTS "Authorized users can delete survey files" ON storage.objects;
CREATE POLICY "Authenticated users can read survey files" ON storage.objects
  FOR SELECT TO authenticated USING (bucket_id = 'survey-documents');
CREATE POLICY "Authorized users can upload survey files" ON storage.objects
  FOR INSERT TO authenticated WITH CHECK (bucket_id = 'survey-documents' AND public.has_action('survey.edit'));
CREATE POLICY "Authorized users can delete survey files" ON storage.objects
  FOR DELETE TO authenticated USING (bucket_id = 'survey-documents' AND public.has_action('survey.edit'));

GRANT EXECUTE ON FUNCTION public.check_survey_overlap(TEXT, BIGINT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_survey_polygon_valid(TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.has_action(TEXT, UUID) TO authenticated;
